#
# World Reset
#  @author Robby Duke
#  @date   01/04/2015
#

whitelistedWorlds:
    - world

scheduledWorlds:
    miningWorld:
      teleportLocation: world
      lastBackup:
      scheduledDays:
      - 15
      - 20
      - 25